### ISSUE TITLE
Question: auto-grow + max height?

### ISSUE THREAD

**Issue by oferRounds** [Paraboly/react-native-input-bar#1]
Hi, the component looks great!

Two quick questions:
1. Does it auto-grow if it needs more than one line?
2. Can you set max height?

**Comment by WrathChaos** [comment]
Hello @oferRounds,
Thank you for these kind words :) 

1. Let me test it and let's see if it is possible with the current one.
2. You can set the maxHeight for the TextInput via `textInputStyle` prop.

**Comment by WrathChaos** [comment]
Hey again @oferRounds,
I've done what you need :) 
Now, InputBar can auto-grow. All you need to do is set `multiline` and set the `height` to `null`. Then it will auto-grow as you wish. 

Also, there are two more new props: `minHeight` and `maxHeight`. 

Please try this new release: 

## [Release 0.1.0 🎉](https://github.com/Paraboly/react-native-input-bar/releases/tag/0.1.0)

**Comment by oferRounds** [comment]
@WrathChaos thank you for these!!!!
I’ll try the new version! Thank you again!

**Comment by WrathChaos** [comment]
@oferRounds, waiting your feedback :)

**Comment by oferRounds** [comment]
Hi @WrathChaos 
Do you know if it’s possible to set the input as an `InputAccessoryView`(the component which is attached to the keyboard, from above)?

**Comment by WrathChaos** [comment]
It was my first thought for this component but I could not make it easily. I will make an accessory for the keyboard soon :) I will inform you. Do you have any inspiration idea?

**Comment by oferRounds** [comment]
I was looking on Wix’s related repositories (there 3 necessary), tried to make it work with them, but they did not work well for me. Couldn’t find so far another inspiration... Looking forward for your solution

**Comment by oferRounds** [comment]
@WrathChaos I might have a way to do it, but so far I‘m getting the error:
```
error: bundling failed: ReferenceError: Module not registered in graph: /Users/ofermorag/Projects/Bob/node_modules/@paraboly/react-native-input-bar/lib/src/InputBar.js
```

Also, no `autoFocus`?

**Comment by WrathChaos** [comment]
Sorry for the late response @oferRounds,
I can make it for autoFocus and maybe for the other features but I need to test for all other ones. Also, I could not reproduce your error. Can you provide with me a minimal reproducible example?

**Comment by WrathChaos** [comment]
Deaer @oferRounds ,
Here is the new design system for flexible TextInput & Spinner :) 
New Design System 🥳
* Complete new design system is here
* More flexible
* TextInput & Spinner are completely under developer's control now

Now, you can use ANY prop for fundamental `TextInput` and `Spinner` :) If you have any improvement, please open a new issue :) 

Please check this new release: 

[## Release 0.1.1 🥳](https://github.com/Paraboly/react-native-input-bar/releases/tag/0.1.1)
