### ISSUE TITLE
Bottom prop is not available anymore

### ISSUE THREAD

**Issue by sepcol** [Paraboly/react-native-input-bar#4]
I really like the input bar!

On the GIT repo and on the npmjs registry I found out there was a bottom prop available to customise the bottom margin for the input-bar. Could this be prop be made available again?

Thanks in advance

**Comment by WrathChaos** [comment]
Hello @sepcol,

Thank you so much for kind words :) I've updated the InputBar. 

https://github.com/Paraboly/react-native-input-bar/releases/tag/0.2.0

Here is the fully typescript version of the InputBar.  You can use `style` for override or write any styling for the InputBar :)
