### ISSUE TITLE
Update to 0.2.0

### ISSUE THREAD

**Issue by sepcol** [Paraboly/react-native-input-bar#5]
Thank you for the update!

I was trying to update the package but now I get the following error:

Metro has encountered an error: While trying to resolve module `@paraboly/react-native-input-bar` from file `/Users/username/Projects/expopagetest/screens/TabTwoScreen.tsx`, the package `/Users/username/Projects/expopagetest/node_modules/@paraboly/react-native-input-bar/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/username/Projects/expopagetest/node_modules/@paraboly/react-native-input-bar/lib/src/InputBar.js`. Indeed, none of these files exist:

  * /Users/username/Projects/expopagetest/node_modules/@paraboly/react-native-input-bar/lib/src/InputBar.js(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * /Users/username/Projects/expopagetest/node_modules/@paraboly/react-native-input-bar/lib/src/InputBar.js/index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)

**Comment by sepcol** [comment]
I have removed my node_modules folder and tried to reinstall from scratch but I'm getting the same issue.

**Comment by sepcol** [comment]
I also saw two different packages for the same 'react-native-input-bar', is this intentionally?

https://www.npmjs.com/package/@paraboly/react-native-input-bar
https://www.npmjs.com/package/@freakycoder/react-native-input-bar

I'm confused now

**Comment by WrathChaos** [comment]
Hello @sepcol, 


> I also saw two different packages for the same 'react-native-input-bar', is this intentionally?
> 
> https://www.npmjs.com/package/@paraboly/react-native-input-bar
> https://www.npmjs.com/package/@freakycoder/react-native-input-bar
> 
> I'm confused now

@freakycoder one is just my fork. You can use it or this one. This one is more based on the company needs. 

Ah, totally my fault. I'm fixing the main path right now so sorry!

**Comment by WrathChaos** [comment]
@sepcol I've fixed it, please try the new version 0.2.1. Totally my mistake forgot to change the new `main path`.

**Comment by sepcol** [comment]
@WrathChaos It works again now! Thanks for the update
