### ISSUE TITLE
OnSubmitEditing prop

### ISSUE THREAD

**Issue by sepcol** [Paraboly/react-native-input-bar#6]
Hey again @WrathChaos 😀

I'm almost complete with integrating your inputbar component in my application! 🥳
It's working really nice at the moment.

The only thing that I'm missing is an option to dismiss the keyboard when I press the return button on the iPhone keyboard.

On a normal TextInput I usually use this to close the keyboard after pressing return:
<TextInput
```
onSubmitEditing={() => 
  {
    Keyboard.dismiss()
  }
}
/>
```

Can this functionality be added to the props?

Thanks in advance

**Comment by WrathChaos** [comment]
Hello @sepcol,
I've done it you can use all of the TextInput props :) 

Here you can see the changes: [Release 0.2.2 🥳](https://github.com/Paraboly/react-native-input-bar/releases/tag/0.2.2)

**Comment by sepcol** [comment]
Hey, TextInput props work perfectly thank you so much for adding this!
I do just spotted an error/crash when I tried to built my app for Android:
'requireNativeComponent: "RNAndrow" was not found in the UIManager'.

I have found this comment: [https://github.com/folofse/androw/issues/19#issuecomment-575147681]

So it turns out I sadly can't use RNAndrow with Expo.
Could you add support for Expo by adding a prop so I can disable the use of RNAndrow? 
Or is this package 100% needed to make the Inputbar working as intented?

Thanks again and sorry for the trouble!

**Comment by WrathChaos** [comment]
Oh, I use Androw for perfect shadow match. I can remove the Androw, it is not mandatory. It is in coming :)

**Comment by sepcol** [comment]
Thanks for the fast response.

Ok I see 🤔.
Ah there is a specific expo version available? I didn't know that yet!
Is it already available somewhere?

**Comment by WrathChaos** [comment]
@sepcol,
I've made the expo version :) 

Please check the documentation: https://github.com/Paraboly/react-native-input-bar#expo-version

All you need to do is change the npm version and add the new dependency :)
