### ISSUE TITLE
Bottom prop on Expo version

### ISSUE THREAD

**Issue by sepcol** [Paraboly/react-native-input-bar#8]
So I'm trying to align the input bar to the bottom of the page (see picture)
But I can't set the bottom prop (on the expo version) to make it so there is no space between the bar and the bottom of the screen, do I need to do something else?
I will also attach my JSX code below.

<img src="https://user-images.githubusercontent.com/72131368/99653212-0b998b00-2a59-11eb-8243-ca6b231901a5.png" width="350" height="auto">

```
<View style={{flex: 1, backgroundColor: 'blue'}}>
                <InputBar multiline={true} maxLength={220} borderRadius={0} style={{width: "100%"}}
                          numberOfLines={4} blurOnSubmit={true} onSubmitEditing={() => {
                    Keyboard.dismiss();
                }} onSendPress={() => {
                    Keyboard.dismiss();
                    setInputText("")
                }} value={inputText} onChangeText={(text) => setInputText(text)} textInputStyle={{
                    fontWeight: 'bold',
                    fontSize: 15,
                    marginTop: 0,
                    marginLeft: 15,
                    marginRight: 55
                }} disableSecondaryIcon={true} placeholder={"Laat hier een reactie achter!                  "}/>
            </View>
```

**Comment by WrathChaos** [comment]
You can override default styling. Simply set `bottom: 0` in style prop. You can even change the `position: absolute` value. You can simply use `style` prop as you want.

**Comment by sepcol** [comment]
I see my bad! This issue can be closed.
