### ISSUE TITLE
Make entire inputbar clickable instead of only text/placeholder text

### ISSUE THREAD

**Issue by sepcol** [Paraboly/react-native-input-bar#9]
Hey @WrathChaos  

I'm very impressed with the component and I really like it in my application! 🥳
I only spotted 1 issue when I was testing my functionality.

So when I want to enter some text in the Inputbar I can only click on the placeholder text.
Can I change something so the keyboard pops up even when I press on the whitespace on the right?

<img src="https://user-images.githubusercontent.com/72131368/99790442-6815ac80-2b24-11eb-88fe-1b96ce2e507c.png" width="350" height="auto">

^On this device the width is not much, but on my android phone I have A LOT of whitespace so I can only enter text whenever I directly press on the placeholder text.

<img src="https://user-images.githubusercontent.com/72131368/99791093-67314a80-2b25-11eb-8044-f03acbd8ea36.png" width="350" height="auto">

This issue becomes even more troublesome when I edit the text and only enter 1 character and then close the keyboard.
Now the space to click on the Inputbar becomes even smaller

I hope I described the issue good enough, if not just let me know 👍 

Thanks for your hard work!

**Comment by WrathChaos** [comment]
Hello @sepcol,
I've tried on example project and it simply auto focus when I press the whitespace part. Can you share with me a minimal reproducible example?

**Comment by sepcol** [comment]
Hmm it's good to hear that it should work.
I'll see if I can create a minimal reproducible example app that I can share.

**Comment by sepcol** [comment]
Maybe it's helpful:

My page consists of a scrollview with items and I display the InputBar on the bottom of the page, so you can see the InputBar wherever u scroll to. 

<ScrollView>
<View style={{flex: 1}}>
                    <InputBar autoCompleteType={"off"} autoCorrect={false} multiline={true} maxLength={220}
                              borderRadius={0}
                              style={keyboardVisible ? {bottom: 70, width: "100%"} : {bottom: 0, width: "100%"}}
                              numberOfLines={4} blurOnSubmit={true} onSubmitEditing={() => Keyboard.dismiss()}
                              onSendPress={() => {
                                  Keyboard.dismiss();
                              }} value={missionDetailAnswer} onChangeText={(text) => setDetailAnswer(text)}
                              textInputStyle={{
                                  fontWeight: 'bold',
                                  fontSize: 15,
                                  marginTop: 0,
                                  marginLeft: 15,
                                  marginRight: 55
                              }} disableSecondaryIcon={true}
                              placeholder={i18n.t("testScreen.addAnswer") + "                                               "}/>
                </View>
</ScrollView

**Comment by WrathChaos** [comment]
@sepcol,

Your `textInputStyle` breaking the TextInput. Do not use `margin`s. Why do you even need them?

**Comment by sepcol** [comment]
@WrathChaos I see...

I added them because otherwise I get this:
<img src="https://user-images.githubusercontent.com/72131368/99813041-7d500280-2b47-11eb-9262-36b94d269ab2.png" width="350" height="auto">

**Comment by sepcol** [comment]
Instead of using the margins like you mentioned, I used padding's and it seems to work perfect 👍
